name: Roy Canseco
title: "roycan pub"
markdown: kramdown
description: a blog
plugins:
  - jekyll-feed
permalink: /blog/:year/:month/:day/:title

google_analytics: UA-42819599-2

collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/


theme: jekyll-theme-architect